"""initial commit

Revision ID: 469b2d591a58
Revises: 
Create Date: 2023-01-09 15:43:38.444301

"""
from alembic import op
import sqlalchemy as sa

import src.app.models.base

# revision identifiers, used by Alembic.
revision = '469b2d591a58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption',
    sa.Column('id', src.app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('enum_id', sa.Enum('fernet', name='encryptionenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enum_id')
    )
    op.create_table('document',
    sa.Column('id', src.app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resource_path', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('encryption_id', src.app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['encryption_id'], ['encryption.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_path')
    )
    op.create_table('keyword',
    sa.Column('id', src.app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('document_id', src.app.models.base.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword')
    op.drop_table('document')
    op.drop_table('encryption')
    # ### end Alembic commands ###
